[project]
name = "mirrorapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "requests>=2.32.4",
    "waitress>=3.0.2",
]
