openapi: 3.0.0
info:
  title: Dynamic Mirror API
  description: A simple REST API that mirrors the request headers and body back to the client. Its behavior can be controlled by special 'request-*' headers.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:4500
    description: Local development server
paths:
  /request:
    summary: Request Echo Endpoint
    description: This endpoint echoes all headers and the body of the request back to the sender. Its behavior is controlled by specific headers.
    get:
      summary: Echo request (GET)
      operationId: getEcho
      parameters:
        - $ref: '#/components/parameters/RequestStatusCode'
        - $ref: '#/components/parameters/RequestWaitTime'
        - $ref: '#/components/parameters/RequestErrorCode'
      responses:
        "200":
          $ref: '#/components/responses/SuccessResponse'
        "201":
          $ref: '#/components/responses/CreatedResponse'
        "500":
          $ref: '#/components/responses/ErrorResponse'
    post:
      summary: Echo request (POST)
      operationId: postEcho
      parameters:
        - $ref: '#/components/parameters/RequestStatusCode'
        - $ref: '#/components/parameters/RequestWaitTime'
        - $ref: '#/components/parameters/RequestErrorCode'
      requestBody:
        description: Request body to be mirrored. Can be any valid JSON.
        content:
          application/json:
            schema:
              type: object
              example:
                key: value
      responses:
        "200":
          $ref: '#/components/responses/SuccessResponse'
        "201":
          $ref: '#/components/responses/CreatedResponse'
        "400":
          $ref: '#/components/responses/BadRequestResponse'
        "500":
          $ref: '#/components/responses/ErrorResponse'
    put:
      summary: Echo request (PUT)
      operationId: putEcho
      parameters:
        - $ref: '#/components/parameters/RequestStatusCode'
        - $ref: '#/components/parameters/RequestWaitTime'
        - $ref: '#/components/parameters/RequestErrorCode'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                key: new_value
      responses:
        "200":
          $ref: '#/components/responses/SuccessResponse'
        "500":
          $ref: '#/components/responses/ErrorResponse'
    delete:
      summary: Echo request (DELETE)
      operationId: deleteEcho
      parameters:
        - $ref: '#/components/parameters/RequestStatusCode'
        - $ref: '#/components/parameters/RequestWaitTime'
        - $ref: '#/components/parameters/RequestErrorCode'
      responses:
        "200":
          $ref: '#/components/responses/SuccessResponse'
        "500":
          $ref: '#/components/responses/ErrorResponse'
    patch:
      summary: Echo request (PATCH)
      operationId: patchEcho
      parameters:
        - $ref: '#/components/parameters/RequestStatusCode'
        - $ref: '#/components/parameters/RequestWaitTime'
        - $ref: '#/components/parameters/RequestErrorCode'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                patch: true
      responses:
        "200":
          $ref: '#/components/responses/SuccessResponse'
        "500":
          $ref: '#/components/responses/ErrorResponse'

components:
  parameters:
    RequestStatusCode:
      in: header
      name: request-statuscode
      schema:
        type: integer
      description: Specifies the HTTP status code for the response. Default is 200.
      example: 201
    RequestWaitTime:
      in: header
      name: request-waittime
      schema:
        type: integer
      description: The number of seconds the service should wait before responding.
      example: 5
    RequestErrorCode:
      in: header
      name: request-errorcode
      schema:
        type: string
      description: Returns an error message and automatically sets the status code to 500.
      example: Service unavailable
  responses:
    SuccessResponse:
      description: The request was successful.
      content:
        application/json:
          schema:
            type: object
            properties:
              received_headers:
                type: object
                description: All headers received from the request.
              received_body:
                type: object
                description: The body of the request.
    CreatedResponse:
      description: The request was successful, and a new resource was created.
      content:
        application/json:
          schema:
            type: object
            properties:
              received_headers:
                type: object
              received_body:
                type: object
    BadRequestResponse:
      description: The request was invalid (e.g., malformed header).
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: A description of the error.
    ErrorResponse:
      description: An internal server error occurred, triggered by 'request-errorcode'.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: The custom error message provided in the header.