apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.deploymentName }}-sv
spec:
  hosts:
    - {{ .Values.istio.host }}
  gateways:
    - {{ .Values.istio.gateway }}
  http:
    - route:
        - destination:
            host: {{ .Values.deploymentName }}
            port:
              number: {{ .Values.service.port }}
